Repository Infomaniak/android-core, pull requests merged in 2022-11, with the labels that each got.

#14 Add Bugs tracker
  BugTracker/.gitignore
  BugTracker/build.gradle
  BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerActivity.kt
  BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerFileAdapter.kt
  BugTracker/src/main/res/drawable/ic_bug_tracker_close.xml
  BugTracker/src/main/res/layout/activity_bug_tracker.xml
  BugTracker/src/main/res/layout/item_bug_tracker_file.xml
  BugTracker/src/main/res/navigation/bug_tracker_navigation.xml
  BugTracker/src/main/res/values-de/strings.xml
  BugTracker/src/main/res/values-es/strings.xml
  BugTracker/src/main/res/values-fr/strings.xml
  BugTracker/src/main/res/values-it/strings.xml
  BugTracker/src/main/res/values/strings.xml
  proguard-rules.pro
  src/main/java/com/infomaniak/lib/core/utils/FilePicker.kt
Labels: feature

#15 Add Matomo tracker from kDrive
  build.gradle
  src/main/java/com/infomaniak/lib/core/MatomoCore.kt
Labels: optimization

#16 Renamed grey tints name with animal names
  src/main/res/values/colors.xml
Labels: enhancement

#20 Add `setMargins` from kDrive
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: optimization
