Repository Infomaniak/android-core, pull requests merged in 2022-07, with the labels that each got.

#10 kMail changes
  build.gradle
  src/main/java/com/infomaniak/lib/core/api/ApiRepositoryCore.kt
  src/main/java/com/infomaniak/lib/core/api/ApiRoutesCore.kt
  src/main/java/com/infomaniak/lib/core/models/ApiError.kt
  src/main/java/com/infomaniak/lib/core/models/ApiResponse.kt
  src/main/java/com/infomaniak/lib/core/utils/ApiController.kt
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
  src/main/java/com/infomaniak/lib/core/utils/LiveDataNetworkStatus.kt
  src/main/java/com/infomaniak/lib/core/utils/UtilsUi.kt
  src/main/res/values/colors.xml
Labels: bug, enhancement, feature

#11 Add Snackbars from kDrive
  src/main/java/com/infomaniak/lib/core/utils/SnackbarUtils.kt
  src/main/res/values-de/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values/strings.xml
Labels: enhancement

#12 Choose custom imageLoader when loading avatar
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: optimization
