Repository Infomaniak/android-core, pull requests merged in 2023-05, with the labels that each got.

#66 Add `KIBI_BYTE` & `KILO_BYTE` constants
  src/main/java/com/infomaniak/lib/core/utils/FormatterFileSize.kt
Labels: feature

#67 Fix Applock for external intent
  AppLock/src/main/java/com/infomaniak/lib/applock/LockActivity.kt
  AppLock/src/main/res/navigation/app_lock_navigation.xml
Labels: enhancement

#69 Rename MainApp
  README.md
Labels: optimization
