Repository Infomaniak/android-core, pull requests merged in 2023-04, with the labels that each got.

#54 fix: Not initialized bearer token for services
  src/main/java/com/infomaniak/lib/core/InfomaniakCore.kt
  src/main/java/com/infomaniak/lib/core/networking/HttpUtils.kt
Labels: enhancement

#56 fix: IllegalArgumentException from safeNavigate for a direction
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: bug

#57 Fix ConnectException for Github, Fdroid and BugTracker calls
  BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerViewModel.kt
  build.gradle
  src/main/java/com/infomaniak/lib/core/fdroidTools/FdroidApiTools.kt
  src/main/java/com/infomaniak/lib/core/githubTools/GitHubViewModel.kt
Labels: bug

#58 Clean Loader views code
  src/main/java/com/infomaniak/lib/core/views/LoaderAdapter.kt
  src/main/java/com/infomaniak/lib/core/views/LoaderCardView.kt
  src/main/java/com/infomaniak/lib/core/views/LoaderConstant.kt
  src/main/java/com/infomaniak/lib/core/views/LoaderController.kt
  src/main/java/com/infomaniak/lib/core/views/LoaderImageView.kt
  src/main/java/com/infomaniak/lib/core/views/LoaderTextView.kt
  src/main/java/com/infomaniak/lib/core/views/LoaderView.kt
Labels: optimization

#59 Handle `maxWidth` for LoaderTextView
  src/main/java/com/infomaniak/lib/core/views/LoaderTextView.kt
Labels: feature

#60 Correct wrong headers
  AppLock/src/main/java/com/infomaniak/lib/applock/Utils.kt
  AppLock/src/main/res/navigation/app_lock_navigation.xml
  BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerViewModel.kt
  BugTracker/src/main/res/drawable/ic_bug_tracker_close.xml
  src/main/java/com/infomaniak/lib/core/MatomoCore.kt
  src/main/java/com/infomaniak/lib/core/githubTools/GitHubRelease.kt
  src/main/java/com/infomaniak/lib/core/githubTools/GitHubViewModel.kt
  src/main/res/drawable-night/splashscreen_branding_image.xml
  src/main/res/drawable/splashscreen_branding_image.xml
Labels: enhancement

#61 Add lockAfterTimeout to LockActivity
  AppLock/src/main/java/com/infomaniak/lib/applock/LockActivity.kt
Labels: feature

#62 Execute `addTrackingCallbackForDebugLog()` only in DEBUG mode
  src/main/java/com/infomaniak/lib/core/MatomoCore.kt
Labels: optimization

#64 Add `Date.isInTheFuture()` function
  build.gradle
  src/main/java/com/infomaniak/lib/core/utils/DateUtils.kt
Labels: feature

#65 Add `ApiErrorCode` data class & store list in InfomaniakCore
  BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerActivity.kt
  src/main/java/com/infomaniak/lib/core/InfomaniakCore.kt
  src/main/java/com/infomaniak/lib/core/api/ApiController.kt
  src/main/java/com/infomaniak/lib/core/utils/ApiErrorCode.kt
Labels: feature
