Repository Infomaniak/android-core, pull requests merged in 2023-09, with the labels that each got.

#87 Differentiate "no network" error
  src/main/java/com/infomaniak/lib/core/api/ApiController.kt
  src/main/res/values-de/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values/strings.xml
Labels: feature

#88 Force Button.showProgress() to display loader centered
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: enhancement

#89 Add italic font
  src/main/res/font/suisseintl_regular_italic.otf
Labels: feature

#91 feat: Add notifyCompat extension
  src/main/AndroidManifest.xml
  src/main/java/com/infomaniak/lib/core/utils/NotificationUtilsCore.kt
Labels: enhancement

#92 fix: kDrive doesn't support the latest version of android-login
  build.gradle
Labels: bug

#90 feat: Capture okhttp api calls with sentry
  build.gradle
  src/main/java/com/infomaniak/lib/core/networking/HttpClient.kt
Labels: feature
