Repository Infomaniak/android-core, pull requests merged in 2023-02, with the labels that each got.

#29 fix: animators may only be run on Looper threads
  BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerActivity.kt
  BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerViewModel.kt
Labels: bug, enhancement

#30 Move `openAppNotificationSettings()` from kDrive to Core
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: optimization

#32 Feat: Get last github release
  BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerActivity.kt
  BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerViewModel.kt
  BugTracker/src/main/res/layout/activity_bug_tracker.xml
  BugTracker/src/main/res/navigation/bug_tracker_navigation.xml
  BugTracker/src/main/res/values-de/strings.xml
  BugTracker/src/main/res/values-es/strings.xml
  BugTracker/src/main/res/values-fr/strings.xml
  BugTracker/src/main/res/values-it/strings.xml
  BugTracker/src/main/res/values/strings.xml
  src/androidTest/java/com/infomaniak/lib/core/HttpUtilsTest.kt
  src/main/java/com/infomaniak/lib/core/api/ApiController.kt
  src/main/java/com/infomaniak/lib/core/githubTools/GitHubRelease.kt
  src/main/java/com/infomaniak/lib/core/githubTools/GitHubViewModel.kt
  src/main/java/com/infomaniak/lib/core/utils/CustomDateTypeAdapter.kt
  src/main/java/com/infomaniak/lib/core/utils/DateUtils.kt
Labels: feature

#33 Fix divider item decorator so it follows recyclerview's notifiy animations
  src/main/java/com/infomaniak/lib/core/views/DividerItemDecorator.kt
Labels: enhancement

#34 Add CoilUtils
  src/main/java/com/infomaniak/lib/core/utils/CoilUtils.kt
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: optimization

#35 Add `showKeyboard` function for Dialogs
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: feature

#36 Get last fdroid release
  src/main/java/com/infomaniak/lib/core/fdroidTools/FdroidApiTools.kt
  src/main/java/com/infomaniak/lib/core/fdroidTools/FdroidRelease.kt
Labels: enhancement
