Repository Infomaniak/android-core, pull requests merged in 2023-03, with the labels that each got.

#37 Move account tracker to core
  src/main/java/com/infomaniak/lib/core/MatomoCore.kt
Labels: enhancement

#38 Close query to avoid leak and download error
  src/main/java/com/infomaniak/lib/core/utils/DownloadManagerUtils.kt
Labels: bug

#41 Update login to 2.7.0
  build.gradle
Labels: feature

#40 Add extensions to transform to camel or snake case
  src/main/java/com/infomaniak/lib/core/MatomoCore.kt
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
  src/main/java/com/infomaniak/lib/core/utils/Utils.kt
Labels: enhancement

#43 Display black colored initials for avatars in dark mode
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
  src/main/java/com/infomaniak/lib/core/utils/UtilsUi.kt
Labels: feature

#44 Fix Core `liveData` version
  build.gradle
Labels: bug

#46 Fix Gson JsonObject serialization
  src/main/java/com/infomaniak/lib/core/api/ApiController.kt
  src/main/java/com/infomaniak/lib/core/models/ApiError.kt
Labels: bug

#47 LoadAvatar can now directly take a background color as argument
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
  src/main/java/com/infomaniak/lib/core/utils/UtilsUi.kt
Labels: enhancement

#48 Create Module for Stores functions
  Stores/build.gradle
  Stores/src/fdroid/java/com.infomaniak.lib.stores/StoreUtils.kt
  Stores/src/standard/java/com.infomaniak.lib.stores/StoreUtils.kt
  build.gradle
  src/main/res/values-de/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values/strings.xml
Labels: enhancement

#51 Change suppressLint by importantForAccessibility
  AppLock/src/main/res/layout/activity_lock.xml
Labels: enhancement

#52 Make `firstOrEmpty()` returns empty strings and not `null` char
  src/main/java/com/infomaniak/lib/core/models/user/User.kt
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: enhancement
