Repository Infomaniak/android-core, pull requests merged in 2023-07, with the labels that each got.

#71 fix: Get file size throw an exception from some devices
  src/main/java/com/infomaniak/lib/core/utils/MediaStoreUtils.kt
Labels: bug, enhancement

#72 Update to kotlin 1.9.0
  build.gradle
Labels: enhancement

#73 Move fix icon padding issue to core
  BugTracker/src/main/res/layout/activity_bug_tracker.xml
  src/main/java/com/infomaniak/lib/core/views/EndIconTextInputLayout.kt
Labels: enhancement

#74 Fix potential Exception thrown by ConnectivityManager on Android 11
  src/main/java/com/infomaniak/lib/core/networking/LiveDataNetworkStatus.kt
Labels: bug

#75 fix: Update bearer token from TokenAuthenticator
  src/main/java/com/infomaniak/lib/core/auth/CredentialManager.kt
Labels: bug, enhancement

#76 Fix divider that was blinking in 1st position
  src/main/java/com/infomaniak/lib/core/views/DividerItemDecorator.kt
Labels: bug

#77 Leave if there is no children
  src/main/java/com/infomaniak/lib/core/views/DividerItemDecorator.kt
Labels: bug
