Repository Infomaniak/android-core, pull requests merged in 2023-10, with the labels that each got.

#93 Add TAG in Sentry breadcrumbs
  src/main/java/com/infomaniak/lib/core/utils/SentryLog.kt
Labels: enhancement

#94 Add extension to automatically clear binding ref
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: optimization

#97 Add `endIconPadding` in `EndIconTextInputLayout`
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
  src/main/java/com/infomaniak/lib/core/views/EndIconTextInputLayout.kt
  src/main/res/values/attrs.xml
  src/main/res/values/dimens.xml
Labels: enhancement

#99 fix: ApiController with custom response throw exceptions in the event of an error.
  src/main/java/com/infomaniak/lib/core/api/ApiController.kt
  src/main/java/com/infomaniak/lib/core/models/ApiResponse.kt
  src/main/java/com/infomaniak/lib/core/models/IApiResponse.kt
  src/main/java/com/infomaniak/lib/core/utils/ApiErrorCode.kt
Labels: bug

#101 Add missing Github workflows
  .github/workflows/auto-author-assign.yml
  .github/workflows/dependent-issues.yml
  .github/workflows/rebase-default-branch.yml
Labels: enhancement
