Repository Infomaniak/android-core, pull requests merged in 2023-08, with the labels that each got.

#79 fix: When the view switches to resume only, the action is ignored
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: bug

#80 Return snackbar object after creating it
  src/main/java/com/infomaniak/lib/core/utils/SnackbarUtils.kt
Labels: enhancement

#82 Uniformize `startActivity` usage
  AppLock/src/main/java/com/infomaniak/lib/applock/LockActivity.kt
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
  src/main/java/com/infomaniak/lib/core/utils/UtilsUi.kt
Labels: optimization

#83 Update navigation lib to 2.7.0
  build.gradle
Labels: enhancement

#84 feat: Add SentryLog
  src/main/java/com/infomaniak/lib/core/utils/SentryLog.kt
Labels: feature

#85 Enhance SentryLog code
  src/main/java/com/infomaniak/lib/core/utils/SentryLog.kt
Labels: optimization
