Repository Infomaniak/android-core, pull requests merged in 2023-11, with the labels that each got.

#102 Add Confetti module
  Confetti/build.gradle
  Confetti/src/main/java/com/infomaniak/lib/confetti/CommonConfetti.kt
  Confetti/src/main/java/com/infomaniak/lib/confetti/ConfettiManager.kt
  Confetti/src/main/java/com/infomaniak/lib/confetti/ConfettiSource.kt
  Confetti/src/main/java/com/infomaniak/lib/confetti/ConfettiView.kt
  Confetti/src/main/java/com/infomaniak/lib/confetti/ConfettoGenerator.kt
  Confetti/src/main/java/com/infomaniak/lib/confetti/Utils.kt
  Confetti/src/main/java/com/infomaniak/lib/confetti/confetto/BitmapConfetto.kt
  Confetti/src/main/java/com/infomaniak/lib/confetti/confetto/CircleConfetto.kt
  Confetti/src/main/java/com/infomaniak/lib/confetti/confetto/Confetto.kt
  Confetti/src/main/java/com/infomaniak/lib/confetti/confetto/ShimmeringConfetto.kt
  Confetti/src/main/res/values/dimens.xml
Labels: feature

#103 Delete FormatterFileSize
  src/main/java/com/infomaniak/lib/core/fdroidTools/FdroidApiTools.kt
  src/main/java/com/infomaniak/lib/core/githubTools/GitHubViewModel.kt
  src/main/java/com/infomaniak/lib/core/utils/FormatterFileSize.kt
Labels: enhancement, dependent

#105 Move strings to core
  BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerFileAdapter.kt
  src/main/res/values-de/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values/strings.xml
Labels: enhancement
