Repository Infomaniak/android-core, pull requests merged in 2024-07, with the labels that each got.

#206 Bump libs
  build.gradle
Labels: optimization

#209 String.removeAccents does not require SKD > 24 anymore
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: enhancement

#207 Fix several SonarCloud issues
  Confetti/src/main/java/com/infomaniak/lib/confetti/ConfettoGenerator.kt
  src/main/java/com/infomaniak/lib/core/utils/Utils.kt
Labels: enhancement

#210 Catch PlayServices AppUpdate exceptions to better understand what's happening
  Stores/src/standard/java/com/infomaniak/lib/stores/AppUpdateScheduler.kt
Labels: bug

#211 Bump libs
  build.gradle
Labels: optimization
