Repository Infomaniak/android-core, pull requests merged in 2024-04, with the labels that each got.

#164 fix: The buildConfig propriety it'll be removed in agp 9
  build.gradle
Labels: feature

#165 Simplify Sentry usage
  Stores/src/standard/java/com/infomaniak/lib/stores/AppUpdateScheduler.kt
Labels: optimization

#168 Add OptOut settings to Matomo tracker
  src/main/java/com/infomaniak/lib/core/MatomoCore.kt
Labels: enhancement

#167 Clean sentry which didn't triggered
  Stores/src/standard/java/com/infomaniak/lib/stores/AppUpdateScheduler.kt
Labels: enhancement

#169 Remove file names and uri from Sentry
  src/main/java/com/infomaniak/lib/core/utils/MediaStoreUtils.kt
Labels: enhancement
