Repository Infomaniak/android-core, pull requests merged in 2024-05, with the labels that each got.

#170 Bump libs
  Stores/build.gradle
  build.gradle
Labels: enhancement

#171 Format some numbers to enhance readability
  AppLock/src/main/java/com/infomaniak/lib/applock/LockActivity.kt
  BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerActivity.kt
  src/main/java/com/infomaniak/lib/core/api/ApiController.kt
  src/main/java/com/infomaniak/lib/core/networking/HttpClientConfig.kt
  src/main/java/com/infomaniak/lib/core/utils/DownloadManagerUtils.kt
Labels: optimization

#174 Add file provider name in MediaStoreUtils's sentry
  src/main/java/com/infomaniak/lib/core/utils/MediaStoreUtils.kt
Labels: enhancement

#173 Put back custom FormatterFileSize to use binary format (1024) instead of SI one (1000)
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
  src/main/java/com/infomaniak/lib/core/utils/FormatterFileSize.kt
Labels: enhancement

#175 Unit tests about custom FormatterFileSize
  build.gradle
  src/test/kotlin/com/infomaniak/lib/core/FormatterFileSizeTest.kt
Labels: feature

#183 Send current textColor to `initProgress()` so it'll be able to restore it when progress is done
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: enhancement

#180 Fix missing custom interceptors and sentry interceptor in some http clients
  src/main/java/com/infomaniak/lib/core/auth/CredentialManager.kt
  src/main/java/com/infomaniak/lib/core/networking/HttpClient.kt
  src/main/java/com/infomaniak/lib/core/networking/HttpClientConfig.kt
  src/main/java/com/infomaniak/lib/core/utils/CoilUtils.kt
Labels: enhancement

#186 Call correct version of `attachTextChangeAnimator()` when there is no color in `initProgress()`
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: bug

#187 Bump versions
  build.gradle
Labels: optimization

#188 Bump more versions
  build.gradle
  src/main/java/com/infomaniak/lib/core/utils/MediaStoreUtils.kt
Labels: optimization

#189 Change import to kotlinx serialization Json Element
  src/main/java/com/infomaniak/lib/core/api/ApiController.kt
Labels: enhancement

#190 Auto-format code
  AppLock/src/main/java/com/infomaniak/lib/applock/Utils.kt
  Stores/src/main/res/layout/activity_feedback_webview.xml
  src/main/java/com/infomaniak/lib/core/utils/Utils.kt
Labels: optimization
