Repository Infomaniak/android-core, pull requests merged in 2024-02, with the labels that each got.

#125 Add possibility to not display DividerItemDecorator depending on the view tag
  src/main/java/com/infomaniak/lib/core/views/DividerItemDecorator.kt
Labels: enhancement

#131 Use DataStore instead of SharedPrefs
  Stores/build.gradle
  Stores/src/main/java/com/infomaniak/lib/stores/BaseInAppUpdateManager.kt
  Stores/src/main/java/com/infomaniak/lib/stores/StoresLocalSettings.kt
  Stores/src/main/java/com/infomaniak/lib/stores/StoresSettingsRepository.kt
  Stores/src/main/java/com/infomaniak/lib/stores/StoresViewModel.kt
  Stores/src/standard/java/com/infomaniak/lib/stores/AppUpdateScheduler.kt
  Stores/src/standard/java/com/infomaniak/lib/stores/updatemanagers/InAppUpdateManager.kt
  Stores/src/standard/java/com/infomaniak/lib/stores/updatemanagers/WorkerUpdateManager.kt
Labels: optimization

#132 Fix bottomsheet being instanced several times
  Stores/src/main/java/com/infomaniak/lib/stores/BaseInAppUpdateManager.kt
  Stores/src/main/java/com/infomaniak/lib/stores/StoresViewModel.kt
  Stores/src/standard/java/com/infomaniak/lib/stores/updatemanagers/InAppUpdateManager.kt
Labels: bug

#133 Add optional no_avatar_default argument when fetching the current user
  src/main/java/com/infomaniak/lib/core/api/ApiRepositoryCore.kt
  src/main/java/com/infomaniak/lib/core/api/ApiRoutesCore.kt
Labels: feature

#135 Update InAppUpdateManagers to support Immediate update
  Stores/src/fdroid/java/com/infomaniak/lib/stores/updatemanagers/InAppUpdateManager.kt
  Stores/src/main/java/com/infomaniak/lib/stores/BaseInAppUpdateManager.kt
  Stores/src/standard/java/com/infomaniak/lib/stores/StoreUtils.kt
  Stores/src/standard/java/com/infomaniak/lib/stores/updatemanagers/InAppUpdateManager.kt
Labels: feature

#134 Add gzip interceptor to be able to unzip API response
  src/main/java/com/infomaniak/lib/core/networking/GZipInterceptor.kt
  src/main/java/com/infomaniak/lib/core/networking/HttpClient.kt
  src/main/java/com/infomaniak/lib/core/networking/HttpUtils.kt
Labels: feature

#138 Make standard flavor the default one
  Stores/build.gradle
Labels: enhancement

#139 Check that api min version is not greater than production version
  Stores/src/main/java/com/infomaniak/lib/stores/updaterequired/data/models/AppPublishedVersion.kt
  Stores/src/main/java/com/infomaniak/lib/stores/updaterequired/data/models/AppVersion.kt
Labels: enhancement

#137 Some Sonar fixes
  src/main/java/com/infomaniak/lib/core/auth/CredentialManager.kt
  src/main/java/com/infomaniak/lib/core/views/LoaderController.kt
Labels: enhancement

#141 Make AppVersion class testable
  Stores/src/main/java/com/infomaniak/lib/stores/updaterequired/data/models/AppVersion.kt
Labels: enhancement
