Repository Infomaniak/android-core, pull requests merged in 2024-06, with the labels that each got.

#193 Fix: When ApiError the context field throws an exception
  src/main/java/com/infomaniak/lib/core/api/ApiController.kt
  src/main/java/com/infomaniak/lib/core/models/ApiError.kt
Labels: bug

#192 Bump versions
  build.gradle
Labels: optimization

#194 Rename FeedbackWebView to Webview and move it out of Stores as it is now used elsewhere
  Stores/src/main/AndroidManifest.xml
  Stores/src/standard/java/com/infomaniak/lib/stores/reviewmanagers/InAppReviewManager.kt
  build.gradle
  src/main/AndroidManifest.xml
  src/main/java/com/infomaniak/lib/core/ui/WebViewActivity.kt
  src/main/res/layout/activity_webview.xml
  src/main/res/navigation/webview_navigation.xml
Labels: optimization

#196 fix: Sometimes no connection is received when multiple are available
  src/main/java/com/infomaniak/lib/core/networking/LiveDataNetworkStatus.kt
Labels: bug

#179 Allow to add custom components on image loader builder
  src/main/java/com/infomaniak/lib/core/utils/CoilUtils.kt
Labels: enhancement

#198 Format regions
  Confetti/src/main/java/com/infomaniak/lib/confetti/CommonConfetti.kt
  Confetti/src/main/java/com/infomaniak/lib/confetti/confetto/Confetto.kt
Labels: optimization

#197 Remove gif preview to use it only in the good project
  build.gradle
  src/main/java/com/infomaniak/lib/core/utils/CoilUtils.kt
Labels: enhancement

#200 Bump versions
  Stores/build.gradle
  build.gradle
Labels: optimization

#199 Lighten version API call
  Stores/src/main/java/com/infomaniak/lib/stores/updaterequired/data/api/ApiRoutesStores.kt
  Stores/src/main/java/com/infomaniak/lib/stores/updaterequired/data/models/AppPublishedVersion.kt
  Stores/src/main/java/com/infomaniak/lib/stores/updaterequired/data/models/AppVersion.kt
Labels: enhancement

#201 Prevent showing and hiding progress crashes
  BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerActivity.kt
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: bug
