Repository Infomaniak/android-core, pull requests merged in 2024-01, with the labels that each got.

#113 Move length parameter after actionButtonTitle for better compatibility
  src/main/java/com/infomaniak/lib/core/utils/SnackbarUtils.kt
Labels: enhancement

#114 Add logs for inAppUpdate
  Stores/src/standard/java/com.infomaniak.lib.stores/StoreUtils.kt
Labels: documentation

#115 Replace values() by entries for kotlin 1.9
  BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerActivity.kt
Labels: enhancement

#117 Transforms shared values util into an interface so we don't need redundant local functions anymore
  src/main/java/com/infomaniak/lib/core/utils/SharedValues.kt
Labels: enhancement

#119 Use initials instead of grey image as Avatars' placeholder
  src/main/java/com/infomaniak/lib/core/utils/Extensions.kt
Labels: enhancement

#120 Add Locale Utils
  src/main/java/com/infomaniak/lib/core/extensions/AppCompatActivityExtensions.kt
  src/main/java/com/infomaniak/lib/core/utils/MediaStoreUtils.kt
Labels: bug

#121 Add Date utils for mail calendar events
  src/main/java/com/infomaniak/lib/core/utils/DateUtils.kt
Labels: feature

#122 Update formatWithLocal
  src/main/java/com/infomaniak/lib/core/utils/DateUtils.kt
Labels: enhancement

#123 Fix Avatar blink because THE SINGLETON WAS NEVER ASSIGNED
  src/main/java/com/infomaniak/lib/core/utils/CoilUtils.kt
Labels: bug, enhancement, feature, optimization
