Repository Infomaniak/android-core, pull requests merged in 2025-02, with the labels that each got.

#262 feat(MyKSuite-02): Upgrade bottomsheet
  MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/components/MyKSuiteChips.kt
  MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/components/WeightOneSpacer.kt
  MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/screens/MyKSuiteUpgradeBottomSheet.kt
  MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/screens/MyKSuiteUpgradeFeature.kt
  MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/screens/components/ButtonType.kt
  MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/screens/components/UpgradeFeature.kt
  MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/theme/ColorsDark.kt
  MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/theme/ColorsLight.kt
  MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/theme/Dimens.kt
  MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/theme/Theme.kt
  MykSuite/src/main/res/drawable-night/illu_banner.xml
  MykSuite/src/main/res/drawable/ic_gift.xml
  MykSuite/src/main/res/drawable/illu_banner.xml
  MykSuite/src/main/res/values-de/strings.xml
  MykSuite/src/main/res/values-es/strings.xml
  MykSuite/src/main/res/values-fr/strings.xml
  MykSuite/src/main/res/values-it/strings.xml
  MykSuite/src/main/res/values/strings.xml
Labels: enhancement

#267 feat(MyKSuite-05): Wrap Dashboard fragment in xml
  MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/screens/MyKSuiteDashboardScreen.kt
  MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/screens/components/LimitedFunctionnalities.kt
  MykSuite/src/main/java/com/infomaniak/lib/myksuite/ui/views/MyKSuiteDashboardFragment.kt
  MykSuite/src/main/res/navigation/my_ksuite_navigation.xml
  MykSuite/src/main/res/values-night/colors.xml
  MykSuite/src/main/res/values/colors.xml
  MykSuite/src/main/res/values/strings.xml
Labels: enhancement

#273 refactor(MyKSuite-08): Delete kSuite theme object
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/components/MyKSuiteChips.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/MyKSuiteDashboardScreen.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/MyKSuiteUpgradeBottomSheet.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/AppStorageQuotas.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/ButtonType.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/ExpandableItemView.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/LimitedFunctionnalities.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/UpgradeFeature.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/UserAvatar.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/Theme.kt
Labels: enhancement

#274 refactor(MyKSuite-09): Mark as internal concerned functions and class that doesn't need to be exposed
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/components/MyKSuitePrimaryButton.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/MyKSuiteUpgradeBottomSheet.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/AppStorageQuotas.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/ExpandableItemView.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/LimitedFunctionnalities.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/MyKSuiteButtonType.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/UpgradeFeature.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/UserAvatar.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/Theme.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/views/MyKSuiteUpgradeBottomSheetDialog.kt
Labels: enhancement

#276 feat(MyKSuite-10): Put all upgrade features in the module
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/MyKSuiteUpgradeBottomSheet.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/MyKSuiteUpgradeFeature.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/AppStorageQuotas.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/MyKSuiteButtonType.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/UpgradeFeature.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/views/MyKSuiteUpgradeBottomSheetDialog.kt
  MykSuite/src/main/res/drawable/ic_drive_cloud.xml
  MykSuite/src/main/res/drawable/ic_enveloppe_italic.xml
  MykSuite/src/main/res/drawable/ic_folder_circle_filled_arrow_up.xml
  MykSuite/src/main/res/drawable/ic_paperplane.xml
  MykSuite/src/main/res/navigation/my_ksuite_navigation.xml
  MykSuite/src/main/res/values-de/strings.xml
  MykSuite/src/main/res/values-es/strings.xml
  MykSuite/src/main/res/values-fr/strings.xml
  MykSuite/src/main/res/values-it/strings.xml
  MykSuite/src/main/res/values/strings.xml
Labels: enhancement

#283 feat: Add ApiEnum and apiEnumValueOfOrNull helper methods
  gradle/core.versions.toml
  src/main/kotlin/com/infomaniak/core/EnumUtils.kt
Labels: enhancement

#285 feat(MyKSuite-12): Add models for api call
  MykSuite/build.gradle.kts
  MykSuite/schemas/com.infomaniak.core.myksuite.ui.data.MyKSuiteDatabase/1.json
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/KSuitePack.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/MyKSuiteData.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/MyKSuiteDataDao.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/MyKSuiteDataManager.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/MyKSuiteDatabase.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/kSuiteDrive.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/kSuiteMail.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/network/ApiRoutes.kt
  gradle/core.versions.toml
Labels: enhancement

#286 feat(MyKSuite-13): Dynamic dashboard
  MykSuite/build.gradle.kts
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/components/TextWithIcon.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/MyKSuiteData.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/network/ApiRoutes.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/MyKSuiteDashboardScreen.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/MyKSuiteUpgradeBottomSheet.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/AppStorageQuotas.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/ExpandableItemView.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/InformationBlock.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/LimitedFunctionnalities.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/MyKSuiteTextItem.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/ProductsStorageQuotas.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/components/UpgradeFeature.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/ColorsDark.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/ColorsLight.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/Dimens.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/Theme.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/views/MyKSuiteDashboardFragment.kt
  MykSuite/src/main/res/drawable/ic_circle_i.xml
  MykSuite/src/main/res/navigation/my_ksuite_navigation.xml
  MykSuite/src/main/res/values/strings.xml
  gradle/core.versions.toml
  src/main/kotlin/com/infomaniak/core/extensions/ContextExt.kt
Labels: enhancement

#287 refactor(myKSuite-14): Clean data models
  MykSuite/schemas/com.infomaniak.core.myksuite.ui.data.MyKSuiteDatabase/1.json
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/KSuitePack.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/MyKSuiteData.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/MyKSuiteDataDao.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/MyKSuiteDataManager.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/kSuiteMail.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/network/ApiRoutes.kt
Labels: enhancement

#275 feat: Update the limit before sending a sentry about access token errors
  Legacy/src/main/java/com/infomaniak/lib/core/auth/TokenInterceptor.kt
  Legacy/src/main/java/com/infomaniak/lib/core/networking/AccessTokenUsageInterceptor.kt
Labels: enhancement

#289 fix(MyKSuite-16): Change navigation to the UpgradeBottomSheet by deeplink
  MykSuite/build.gradle.kts
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/views/MyKSuiteUpgradeBottomSheetDialog.kt
  MykSuite/src/main/res/navigation/my_ksuite_navigation.xml
  src/main/kotlin/com/infomaniak/core/extensions/StringExt.kt
Labels: enhancement

#291 chore: Downgrade core's minsdk to 21
  build.gradle.kts
Labels: enhancement

#295 chore(MailQuotasApiFix): Remove the need for an api fix for mail quota
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/data/kSuiteMail.kt
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/utils/MyKSuiteUiUtils.kt
Labels: enhancement

#297 chore: Rename ic_envelope to avoid having bad resource merge in Mail
  MykSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/MyKSuiteDashboardScreen.kt
  MykSuite/src/main/res/drawable/ic_envelope_bold.xml
Labels: bug

#301 feat: Add a delegate to read and mutate an apiEnum backingfield seamlessly
  src/main/kotlin/com/infomaniak/core/utils/EnumUtils.kt
Labels: enhancement

#303 feat(Matomo): Add tracker utils
  MyKSuite/src/main/java/com/infomaniak/core/myksuite/ui/utils/MatomoMyKSuite.kt
Labels: feature
