Repository Infomaniak/android-core, pull requests merged in 2025-08, with the labels that each got.

#475 feat: Create a module for the BasicButton component
  Compose/BasicButton/build.gradle.kts
  Compose/BasicButton/src/main/kotlin/com/infomaniak/core/compose/basicbutton/BasicButton.kt
Labels: enhancement

#489 feat: Expose easy to reuse onboarding components
  Avatar/src/main/java/com/infomaniak/core/avatar/components/Avatar.kt
  Compose/BasicButton/src/main/kotlin/com/infomaniak/core/compose/basicbutton/BasicButton.kt
  Compose/Basics/src/main/kotlin/com/infomaniak/core/compose/basics/ButtonStyle.kt
  CrossAppLogin/Back/src/main/kotlin/com/infomaniak/core/crossapplogin/back/BaseCrossAppLoginViewModel.kt
  CrossAppLogin/Front/build.gradle.kts
  CrossAppLogin/Front/src/main/kotlin/com/infomaniak/core/crossapplogin/front/components/CrossLoginAvatar.kt
  CrossAppLogin/Front/src/main/kotlin/com/infomaniak/core/crossapplogin/front/components/CrossLoginBottomContent.kt
  CrossAppLogin/Front/src/main/kotlin/com/infomaniak/core/crossapplogin/front/components/PrimaryButton.kt
  CrossAppLogin/Front/src/main/kotlin/com/infomaniak/core/crossapplogin/front/components/SelectedAccountsButton.kt
  CrossAppLogin/Front/src/main/kotlin/com/infomaniak/core/crossapplogin/front/data/CrossLoginCustomization.kt
  CrossAppLogin/Front/src/main/kotlin/com/infomaniak/core/crossapplogin/front/icons/ArrowRight.kt
  CrossAppLogin/Front/src/main/kotlin/com/infomaniak/core/crossapplogin/front/views/CrossLoginListAccountsView.kt
  CrossAppLogin/Front/src/main/kotlin/com/infomaniak/core/crossapplogin/front/views/CrossLoginSelectAccountsView.kt
  CrossAppLogin/Front/src/main/kotlin/com/infomaniak/core/crossapplogin/front/views/components/CrossLoginListAccounts.kt
  CrossAppLogin/Front/src/main/kotlin/com/infomaniak/core/crossapplogin/front/views/components/CrossLoginSelectAccounts.kt
  CrossAppLogin/Front/src/main/res/values-de/strings.xml
  CrossAppLogin/Front/src/main/res/values-es/strings.xml
  CrossAppLogin/Front/src/main/res/values-fr/strings.xml
  CrossAppLogin/Front/src/main/res/values-it/strings.xml
  CrossAppLogin/Front/src/main/res/values/strings.xml
  Onboarding/build.gradle.kts
  Onboarding/src/main/kotlin/com/infomaniak/core/onboarding/HorizontalPagerIndicator.kt
  Onboarding/src/main/kotlin/com/infomaniak/core/onboarding/OnboardingScaffold.kt
  Onboarding/src/main/kotlin/com/infomaniak/core/onboarding/components/OnboardingComponents.kt
  gradle/core.versions.toml
Labels: feature

#496 feat: Display initials while in the loading state when loading an url avatar
  Avatar/src/main/java/com/infomaniak/core/avatar/components/UrlAvatar.kt
Labels: bug, enhancement

#499 chore: Bump libs
  gradle/core.versions.toml
Labels: enhancement

#500 chore: Bump github actions versions and add concurrency groups
  .github/workflows/auto-author-assign.yml
  .github/workflows/dependent-issues.yml
  .github/workflows/rebase-default-branch.yml
  .github/workflows/semantic-commit.yml
Labels: enhancement

#501 fix: Downgrade kotest version requiring kotlin 2.2.0
  gradle/core.versions.toml
Labels: bug
