Repository Infomaniak/android-core, pull requests merged in 2025-05, with the labels that each got.

#342 feat(SDK35): Support edge to edge
  Legacy/BugTracker/src/main/java/com/infomaniak/lib/bugtracker/BugTrackerActivity.kt
  Legacy/Stores/src/main/res/layout/activity_update_required.xml
  Legacy/src/main/res/layout/activity_webview.xml
Labels: enhancement

#340 feat: Deprecate ApiResponse.translatedError
  Legacy/src/main/java/com/infomaniak/lib/core/api/ApiController.kt
  Legacy/src/main/java/com/infomaniak/lib/core/api/InternalTranslatedErrorCode.kt
  Legacy/src/main/java/com/infomaniak/lib/core/models/ApiResponse.kt
  Legacy/src/main/java/com/infomaniak/lib/core/utils/ApiErrorCode.kt
Labels: enhancement

#358 chore: Add warning to avoid bumping libs that'll break apps
  Legacy/Stores/build.gradle
  gradle/core.versions.toml
Labels: enhancement

#359 fix: Change modifier order to avoid white spacing in landscape
  MyKSuite/src/main/java/com/infomaniak/core/myksuite/ui/screens/MyKSuiteDashboardScreen.kt
Labels: bug

#365 feat: Use new valid email detection regex that matches closer to RFC5321
  src/main/kotlin/com/infomaniak/core/utils/EmailUtils.kt
Labels: enhancement

#354 feat: Add edge-to-edge support and remove backups for the WebView module
  WebView/build.gradle.kts
  WebView/src/main/AndroidManifest.xml
  WebView/src/main/kotlin/com/infomaniak/core/webview/ui/WebViewActivity.kt
  WebView/src/main/kotlin/com/infomaniak/core/webview/ui/components/WebView.kt
Labels: enhancement

#355 feat: Add in-app review module
  InAppReview/build.gradle.kts
  InAppReview/proguard-rules.pro
  InAppReview/src/fdroid/kotlin/com/infomaniak/core/inappreview/reviewmanagers/InAppReviewManager.kt
  InAppReview/src/main/kotlin/com/infomaniak/core/inappreview/AppReviewSettingsRepository.kt
  InAppReview/src/main/kotlin/com/infomaniak/core/inappreview/BaseInAppReviewManager.kt
  InAppReview/src/standard/kotlin/com/infomaniak/core/inappreview/reviewmanagers/InAppReviewManager.kt
  gradle/core.versions.toml
  src/main/res/values-de/strings.xml
  src/main/res/values-es/strings.xml
  src/main/res/values-fr/strings.xml
  src/main/res/values-it/strings.xml
  src/main/res/values/strings.xml
Labels: enhancement

#369 fix(InAppReview): Fix fdroid variant for InAppReview Module
  InAppReview/src/fdroid/kotlin/com/infomaniak/core/inappreview/reviewmanagers/InAppReviewManager.kt
  InAppReview/src/main/kotlin/com/infomaniak/core/inappreview/BaseInAppReviewManager.kt
  InAppReview/src/standard/kotlin/com/infomaniak/core/inappreview/reviewmanagers/InAppReviewManager.kt
Labels: enhancement

#367 feat: Automatically define a jetpack compose MaterialTheme based on the theme defined in xml
  Compose/MaterialThemeFromXml/build.gradle.kts
  Compose/MaterialThemeFromXml/src/main/kotlin/com/infomaniak/core/compose/materialthemefromxml/MaterialThemeFromXml.kt
Labels: feature

#371 refactor: Use the new MaterialThemeFromXml inside MyKSuite module
  MyKSuite/build.gradle.kts
  MyKSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/ColorsDark.kt
  MyKSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/ColorsLight.kt
  MyKSuite/src/main/java/com/infomaniak/core/myksuite/ui/theme/Theme.kt
Labels: enhancement
